version: '3.1'
services:
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      - PGWEB_ADDRESS=foo.example.org
      - PGWEB_BASICAUTH_USER=admin
      - PGWEB_BASICAUTH_PASSWORD=$$2a$$14$$fZMO2Xnas8NCZRyJRq80/.JH74PTmP0GKZjkUo8E4HZDRO/cBGnGy
    ports:
      - "443:443"
      - "80:80"
    links:
      - pgweb:pgweb
    depends_on:
      - pgweb
    volumes:
      - caddy-data:/data
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: unless-stopped
    links:
      - postgis:postgis
    environment:
      - PGWEB_LOCK_SESSION=1
      - PGWEB_DATABASE_URL=postgres://postgres:c64ccUDl52S2n1Xbp70qq6HNxQ4@postgis:5432/workspace?sslmode=disable
    depends_on:
      - postgis

  postgis:
    container_name: postgis
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    shm_size: 1g
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=c64ccUDl52S2n1Xbp70qq6HNxQ4
      - POSTGRES_DB=workspace
    volumes:
      - /data/db:/var/lib/postgresql/data
      - /data/exchange:/exchange
    ports:
      - "5432:5432"

volumes:
  caddy-data: